### ISSUE TITLE
对“venv”文件夹的识别，不只是“env”

### ISSUE THREAD

**Issue by BernieHuang2008** [yuka-friends/Windrecorder#10]
https://github.com/Antonoko/Windrecorder/blob/main/start_record.bat#L5

是不是可以识别env或者venv，两个名字都可以？

众所周知，pycharm的虚拟环默认是venv

**Comment by Clouder0** [comment]
或者可以考虑使用 poetry、pdm 等工具构建项目(

**Comment by jpswing** [comment]
我们已使用了 poetry 生成的虚拟环境，这个 issue 不再 valid
