### ISSUE TITLE
bug: 托盘显示"WebUI started failed"且无webui错误日志

### ISSUE THREAD

**Issue by panshaowu** [yuka-friends/Windrecorder#109]
OS: Windows 11
Python: 3.11.7
Commit ID: c5661ad206a759e9b312d45d90ad11ac5ea6ca29

问题描述：
1. start_app.bat拉起程序（之前已使用install_update.bat更新）
2. 右键单击托盘，选择“启动搜索/设置界面”
3. 10s后提示“WebUI started failed”，大意是拉起webui超过10s，建议查看cache目录下的错误日志
4. webui.err文件为空，webui.log文件内只有Welcome to Streamlit!信息，recording.log和recording.err中亦无报错信息
5. cmd界面内亦无错误信息：
``` text
No conda env active, defaulting to base
files: folder existed:cache
files: folder existed:cache\logs
files: folder existed:cache\locks
files: folder existed:cache\locks\LOCK_MAINTAIN
```

怀疑根因：
1. Windows 11 OS适配问题？
2. python采用miniconda3搭建，引入了适配问题？

建议：
1. 提供更多的错误日志供用户/开发者分析
2. 目前大部分新计算机出厂预装的为Windows 11，建议考虑适配

**Comment by Antonoko** [comment]
感谢详实的反馈！我们昨天认为问题出在streamlit在第一次启动时会有收集邮箱的步骤提示，这个提示会阻塞正常启动。可以先试试在Windrecorder目录下建立一个test.py，内容如下：
```
import streamlit as st
st.text('hi')
```
之后在Windrecorder目录下打开命令行，执行：
```
poetry shell
streamlit run test.py
```
之后见到streamlit收集邮箱的提示后，直接回车跳过，关闭终端，再尝试从托盘启动webui应该就能跳过这个阻塞性错误啦

**Comment by Antonoko** [comment]
@jpswing 看上去 https://github.com/yuka-friends/Windrecorder/commit/c5661ad206a759e9b312d45d90ad11ac5ea6ca29 这个修复还是无法跳过streamlit的营销收集，导致未跳过这一步时必现启动失败。
![image](https://github.com/yuka-friends/Windrecorder/assets/11193477/50165938-7905-47e3-95df-154d77794004)

**Comment by panshaowu** [comment]
> ```
> streamlit run webui.py
> ```

谢谢回复。按照上述操作后，能够正常启动webui了。
另外，Windows10 OS上也复现了该问题，期待及早修复。
