### ISSUE TITLE
feat: 移除（一日之时）词云统计

### ISSUE THREAD

**Issue by Antonoko** [yuka-friends/Windrecorder#129]
感觉提供信息增量并不大，高频统计的信息多为 UI copywriting，而非聚焦到内容，需要大而全面的stop word才能规避；此外分词所需时间与占用资源都比较高。在有更有的 wintitle 统计情况下可以考虑先移除每日的词云统计🤔或将统计来源从所有 OCR 文本改为 wintitle的统计（也行不通，这样所有都是 Google Chrome 了【

![image](https://github.com/yuka-friends/Windrecorder/assets/11193477/72f1a030-f0d7-46a4-822d-ab7c3d890231)

**Comment by ASC8384** [comment]
但按照这种逻辑，是不是每月的词云也得去除？

**Comment by Antonoko** [comment]
> 但按照这种逻辑，是不是每月的词云也得去除？

我也觉得，感觉目前的词云统计都是脏数据。不过看了下词云的依赖并不是特别大，主要是数据集选的不够好，不应该用raw ocr的内容来统计，而应该统计窗口标题会比较有趣些？（不过窗口标题的词频可能没有特别大的意义，说到底还是图一乐。如果一乐也图不了移除也可以haha

**Comment by ASC8384** [comment]
感觉可以列个每日 top_k 的词汇表，然后选择是否加入停用词
~~既然图一乐，感觉可以把这个加回来，不然粒度太大了点~~

**Comment by Antonoko** [comment]
目前词云的问题可能是 top_k 的词汇表都是固定那些 UI copywriting，于是导致每天每月最顶部的结果都差不多，没能反映总结出到底看了啥内容 lol。难点一个是如何洗数据；另一个是 top_k 词汇表中，每个单词表意上信息含量感觉太少、太以偏概全了（就一个词汇能说明什么呢🤔），最理想还得是 LLM 总结所有文本/窗口标题我认为哈哈
