### ISSUE TITLE
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'C:\\Python311\\Scripts\\dul-receive-pack' Consider using the `--user` option or check the permissions.   [notice] A new release of pip is available: 23.2.1 -> 24.0 [notice] To update, run: python.exe -m pip install --upgrade pip C:\Python311\python.exe: No module named poetry.__main__; 'poetry' is a package and cannot be directly executed C:\Python311\python.exe: No module named poetry.__main__; 'poetry' is a package and cannot be directly executed C:\Python311\python.exe: No module named poetry.__main__; 'poetry' is a package and cannot be directly executed Traceback (most recent call last):   File "D:\Windrecorder-main\\onboard_setting.py", line 7, in <module>     from windrecorder import utils   File "D:\Windrecorder-main\windrecorder\utils.py", line 16, in <module>     import cv2 ModuleNotFoundError: No module named 'cv2' 请按任意键继续. . .

### ISSUE THREAD

**Issue by jackylee1** [yuka-friends/Windrecorder#135]
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'C:\\Python311\\Scripts\\dul-receive-pack'
Consider using the `--user` option or check the permissions.

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
C:\Python311\python.exe: No module named poetry.__main__; 'poetry' is a package and cannot be directly executed
C:\Python311\python.exe: No module named poetry.__main__; 'poetry' is a package and cannot be directly executed
C:\Python311\python.exe: No module named poetry.__main__; 'poetry' is a package and cannot be directly executed
Traceback (most recent call last):
  File "D:\Windrecorder-main\\onboard_setting.py", line 7, in <module>
    from windrecorder import utils
  File "D:\Windrecorder-main\windrecorder\utils.py", line 16, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
请按任意键继续. . .

**Comment by Antonoko** [comment]
谢谢反馈，看上去是 `poetry` 没能成功安装。我添加上了清华镜像源，请试试在目录下命令行使用 `git pull` 更新代码后、删除文件夹下的 .venv（如有），重新运行 `install_update.bat` 脚本安装

**Comment by EthanKeng** [comment]
I am having the similar issue.... I just clone the repo today, should be latest one. 

`Traceback (most recent call last):
  File "C:\Users\jojo7\Documents\Windrecorder\\onboard_setting.py", line 7, in <module>
    from windrecorder import __version__, utils
  File "C:\Users\jojo7\Documents\Windrecorder\windrecorder\utils.py", line 16, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Press any key to continue . . .`
