### ISSUE TITLE
feature: h265/硬件加速

### ISSUE THREAD

**Issue by myshzzx** [yuka-friends/Windrecorder#136]
可以考虑压成 .H265, 同等画质存储减少一半

- 开启硬件加速: `-hwaccel auto`
- CPU: `-c:v libx265 -x265-params crf=28`
- nVIDIA : `-c:v hevc_nvenc -qp 28`
- AMD: `-c:v hevc_amf -qp_p 28 -qp_i 28 `

**Comment by Antonoko** [comment]
感谢建议！已合入更新~
https://github.com/yuka-friends/Windrecorder/pull/134
