### ISSUE TITLE
[bug]安装插件后无法识别｜无法修改视频压缩配置

### ISSUE THREAD

**Issue by dangehub** [yuka-friends/Windrecorder#144]
问题1:安装图像语义检索模块后（install脚本无报错），重启app且重启电脑后，都无法在设置中找到“启用”选项，并且在全局搜索中提示“未启用或未安装图像语义检索模块，请前往设置页启用。若设置中无相关选项，请先安装图像语义模块。安装脚本位于 Windrecorder 目录下：extension\install_img_embedding_module\install_img_embedding_module.bat”

问题2:在设置【录制与视频存储】中测试了支持的编号方式，确定我的电脑支持265 nvenc，修改并保存设置后，重启app发现设置又回到了默认的【264 cpu】，经过观察发现`\\Windrecorder\userdata\config_user.json`配置文件会在保存后修改，但是重启后会回滚到之前的配置文件，而`\\Windrecorder\config\config_user.json`这个配置文件中没有关于视频压缩的相关参数。

**Comment by Antonoko** [comment]
感谢反馈！看上去是`config_user.json`被覆写了，可以更新一下应用试试😱。
（目前的读取逻辑为，如果检测到有位于`config\config_user.json`的旧配置文件，则移动到新的`userdata\config_user.json`位置；若无，则在`userdata\config_user.json`创建默认配置文件。如果是旧版本、遗留有`config\config_user.json`，可以试着删除。）
- 安装图像语义检索模块后，`config_user.json`中的`img_embed_module_install`、`enable_img_embed_search`、`enable_synonyms_recommend`会被设置为`true`，若无可以手动更改一下试试🫡。（应该也是没能写入成功配置…好神秘
- 压缩编码方式在 `config_user.json`中的配置项为：`compress_encoder`，`compress_accelerator`，`compress_quality`，作为参考

如果以上方法都不生效，可以试试全新安装一遍工具：在下载后先在目录下创建userdata文件夹，然后将过去的db、result_lightbox、result_timeline、result_wintitle、result_wordcloud、videos、config_user.json、flag_mark_note.csv等文件夹移入其中，之后正常安装后使用。（需要保持与之前起的用户名一致，才能正确读到数据库，用户名为db内文件的前缀

**Comment by dangehub** [comment]
> 感谢反馈！看上去是`config_user.json`被覆写了，可以更新一下应用试试😱。 （目前的读取逻辑为，如果检测到有位于`config\config_user.json`的旧配置文件，则移动到新的`userdata\config_user.json`位置；若无，则在`userdata\config_user.json`创建默认配置文件。如果是旧版本、遗留有`config\config_user.json`，可以试着删除。）
> 
> * 安装图像语义检索模块后，`config_user.json`中的`img_embed_module_install`、`enable_img_embed_search`、`enable_synonyms_recommend`会被设置为`true`，若无可以手动更改一下试试🫡。（应该也是没能写入成功配置…好神秘
> * 压缩编码方式在 `config_user.json`中的配置项为：`compress_encoder`，`compress_accelerator`，`compress_quality`，作为参考
> 
> 如果以上方法都不生效，可以试试全新安装一遍工具：在下载后先在目录下创建userdata文件夹，然后将过去的db、result_lightbox、result_timeline、result_wintitle、result_wordcloud、videos、config_user.json、flag_mark_note.csv等用户数据文件夹移入其中，之后正常安装后使用。（需要保持与之前起的用户名一致，才能正确读到数据库，用户名为db内文件的前缀

感谢，最后重装就好了，应该是升级过程中有老文件残留了。
