### ISSUE TITLE
the use of Chinese and English in the same documents

### ISSUE THREAD

**Issue by chris9672** [yuka-friends/Windrecorder#154]
I think the app is very good and promising, but it's not really good to use Chinese and English together in one document,
e.g. in github. Google Translate is actually very good. However, when two different languages are used in the same
document, quite strange translations can occur. Since English is also used I'd suggest using English for the entire project
(on all Github pages). The vast majority of developers probably won't even need an online translator then.
If for some reason it is not possible to keep the entire project in English, I'd suggest keeping it entirely in Chinese, with
no English words in between. I don't speak Chinese, but Google translations are definitely more understandable when
Google only has to focus on one language to translate.

**Btw, the app is really promising, especially considering that it seems to be at the beginning of development.**

**Comment by Antonoko** [comment]
Thanks for the feedback. Mixed multilingual readme will indeed bring quality loss to the translator. I have set the English version of the readme as the main README, which should improve the quality of the default translation. Considering users from China, a separate Chinese version of the readme document will still be retained.

**Comment by chris9672** [comment]
> Thanks for the feedback. Mixed multilingual readme will indeed bring quality loss to the translator. I have set the English version of the readme as the main README, which should improve the quality of the default translation. Considering users from China, a separate Chinese version of the readme document will still be retained.

That's an excellent idea
