### ISSUE TITLE
建议添加识别某应用在前台时，停止录制视频

### ISSUE THREAD

**Issue by 1298345095** [yuka-friends/Windrecorder#161]
例如识别vscode几个字来判断，并不可靠。

**Comment by Antonoko** [comment]
你好！由于现在的机制是录制完整的15分钟片段再进行处理，而非最理想化的先截图再拼接为视频，因此当用户在不同前台应用间较频繁切换、且其中有应用名在跳过列表上时，停止录制与重新开始录制视频可能会让文件比较琐碎。

目前做法是如果前台应用名在列表上，虽然在这个录制周期中仍然会录制到视频中，但不会被 OCR 索引到数据库、不会被搜索到。如果在下一个视频片段开始录制时、仍停留在这个应用，则下一个视频片段不会开始录制，直到离开这个应用。（因此如果一直停留在这个应用，最多可能会有15分钟的暂停录制延迟）。目前这个策略主要是为了跳过在游戏等较专注沉浸的应用中进行录制，同时密码、信用卡支付等明文敏感信息不会被写到数据库中。如果未来重构为了先截图缓存再拼接为视频，应该就能有更灵活的控制方式了。

**Comment by 1298345095** [comment]
场景例如边开着游戏直播，边做其他工作，在专注于看直播，即直播在前台时可以停止录制。而切换到工作应用时继续录制。因为游戏画面变化剧烈，会导致录制视频体积大幅增加，希望能优化。
我的想法是可以在ffmpeg录制屏幕时同时记录前台应用的变化情况，录制完成后根据变化情况进行剪切删除，如果担心视频太过碎片的话可以填充黑画面之类的。ffmpeg应该很容易实现该功能。
如果要有更好的效果，可以记录前台应用的位置，只保留该应用的画面，或者把设置好的某应用画面录制为黑色。若是不需要上述的效果，也可以实现只录制前台应用，桌面背景之类的不进行录制的功能。

**Comment by Antonoko** [comment]
久等了！支持仅录制前台活动窗口、能根据截图帧自动识别与判断、具有更低能耗和更灵活的“自动灵活截图（使用 MSS）”模式已加入，欢迎更新尝试~
