### ISSUE TITLE
我可以把这个项目用于UI自动化回放吗

### ISSUE THREAD

**Issue by Justwannasleep** [yuka-friends/Windrecorder#170]
我有一个项目需要做UI自动化，这个项目的前端是出于迭代过程的。所以我担心在回放过程里遇到UI与上次成功的case不一致的情况（ 但是自动化流程是能走通的）。所以我想问问这个项目帮助我检索出这种区别吗？

**Comment by Antonoko** [comment]
这种情况下，感觉直接使用 ffmpeg 录制或者定时截图可能更加灵活可控一些？这个项目的录制部分目前比较笨、不够灵活，主要目的也仅为了个人资料的记录回溯，可能比较难以泛化和定制到其他场景中。
