### ISSUE TITLE
有动态壁纸时会把动态壁纸全部录进去

### ISSUE THREAD

**Issue by 1298345095** [yuka-friends/Windrecorder#172]
能否考虑不用ffmpeg的录屏方式，将录屏时的桌面背景捕捉成黑色之类的

**Comment by Antonoko** [comment]
感谢反馈！对于动态壁纸，目前的录制方式没有太好的应对办法……当位于桌面时、窗口标题会得到空结果，因此无法通过检测窗口标题的方式跳过录制，同时因为画面仍然在运动，不会触发画面检测暂停。目前我做法是在离开电脑前锁屏、或者开一个chrome的空标签页放在前台（提前把chrome标签页窗口标题加入到跳过名单）

未来希望可以改变录屏的方式，比如只对活跃的窗口进行截图，不录制整个屏幕，从而拥有更高控制自由度。（感觉是比较大的重构和开发工程，不确保会不会有时间精力改造…🫠）（如果有意愿兴趣的朋友们看到欢迎一起改进

**Comment by Antonoko** [comment]
久等了！支持仅录制前台活动窗口的“自动灵活截图（使用 MSS）”模式已加入，欢迎更新尝试~
