### ISSUE TITLE
Suggest this project be portable to Linux

### ISSUE THREAD

**Issue by johnblommers** [yuka-friends/Windrecorder#174]
Congratulations on building Windrecorder.

Will the developers kindly consider providing instructions to build and run Windrecorder on Linux.

That would be awesome!

I'm seeing Windrecorder as the free, open source, optional install, run anywhere, telemetry-free, and AI-free alternative to the invasive closed-source Microsoft Recall that only works under Windows on Qualcomm PCs.

**Comment by Antonoko** [comment]
Thank you for your attention! Limited by my usage environment, time and energy, as well as the historical burden of the project, this project may focus on Windows.

On Linux, I would recommend this project, which has an interface and functions close to Rewind, as well as support for LLM ai: https://github.com/apirrone/Memento

Beside, I have added similar products I have seen to README, feel free to refer:

- Windows:
     - (commercial) https://timesnapper.com/
     - (commercial) https://www.manictime.com/
     - (commercial) https://apse.io/
- Linux:
     - (open source) https://github.com/apirrone/Memento
- MacOS:
     - (open source) https://github.com/jasonjmcghee/rem
     - (commercial) https://screenmemory.app
     - (commercial) https://www.rewind.ai/
- Android:
     - (free, in-app purchases) https://play.google.com/store/apps/details?id=io.github.mthli.snapseek

**Comment by johnblommers** [comment]
Thank you for your helpful reply!
