### ISSUE TITLE
在microsoft edge上无法回放视频

### ISSUE THREAD

**Issue by ertutio** [yuka-friends/Windrecorder#177]
我目前使用的edge版本是版本 125.0.2535.85 ，但是在edge中打开webui，回放视频会一直黑屏加载，但在chrome125.0.6422.141这一版本中打开webui可以正常观看回放

**Comment by ertutio** [comment]
![123](https://github.com/yuka-friends/Windrecorder/assets/161028206/669f2504-8fe0-4c71-9e6c-848d17b6b00a)
edge上出现的问题如图

**Comment by ertutio** [comment]
> 我目前使用的edge版本是版本 125.0.2535.85 ，但是在edge中打开webui，回放视频会一直黑屏加载，但在chrome125.0.6422.141这一版本中打开webui可以正常观看回放

刚刚对edge进行了重置设置，依旧存在这个问题

**Comment by ASC8384** [comment]
能不能调出开发者工具，看一下控制台输出的信息

**Comment by ertutio** [comment]
[localhost-1717485401279.log](https://github.com/user-attachments/files/15544000/localhost-1717485401279.log)我刚看了一下，就是复制网页里指向的视频链接edge里也是黑屏不能加载，在chorme里可以打开

**Comment by ertutio** [comment]
![456](https://github.com/yuka-friends/Windrecorder/assets/161028206/527e390f-0d9a-47f3-b9da-bab8a901a319)
![789png](https://github.com/yuka-friends/Windrecorder/assets/161028206/c2e11207-2459-41aa-bd3f-b56f10d9b3de)很奇怪同样的视频链接在edge里死活不加载，在chrome里可以

**Comment by ertutio** [comment]
> 能不能调出开发者工具，看一下控制台输出的信息

问题已定位，跟edge浏览器无法解码hevc格式视频有关，建议在后续版本切换编码时候提示一下

**Comment by Antonoko** [comment]
> > 能不能调出开发者工具，看一下控制台输出的信息
> 
> 问题已定位，跟edge浏览器无法解码hevc格式视频有关，按照网上相关教程设置之后已解决，建议在后续版本切换视频编码时候提示一下浏览器的解码支持问题

感谢好提议，已添加~
