### ISSUE TITLE
I still have a lot of lockscreen footage in my memory

### ISSUE THREAD

**Issue by enzon19** [yuka-friends/Windrecorder#179]

**Comment by Antonoko** [comment]
Thanks for the feedback! We have tried to fix the problem, feel free to update the app and try again.

Here is how to manually check whether the lock screen detection is useful:
1. Create a new `test.py` file with the following content in the root directory of windrecorder
```python
import time
from windrecorder import utils

while(True):
    if utils.is_screen_locked():
        print("Locked")
    else:
        print("Not locked")
    time.sleep(1)
```
2. Execute `poetry shell` in the directory, and then execute `python test.py`
3. The script will check whether the screen is locked every second. You can lock the screen and then return to check the detection results during the process
