### ISSUE TITLE
疑问：SVT-AV1和NV_H265哪个更有优势？

### ISSUE THREAD

**Issue by 1298345095** [yuka-friends/Windrecorder#191]
SVT-AV1用的是CPU，CPU性能占用会比较高。但是NV_H265应该用的是独显，能空出CPU来。
但两个的编码效率不一样，体积也不一样，很难判断orz，尤其是laptop，额外为了录制视频开启独显，很难取舍了。。

**Comment by 1298345095** [comment]
话说以前我记得它不是全分辨率录制的，现在好像默认全分辨率了？帧率倒是下去了，不过总比模糊好

**Comment by ASC8384** [comment]
编码目前还没有一个完美的标准，您不妨先根据实际使用场景，每个标准都试一段时间，根据文件体积以及电脑性能来断决

**Comment by Antonoko** [comment]
> 话说以前我记得它不是全分辨率录制的，现在好像默认全分辨率了？帧率倒是下去了，不过总比模糊好

对的，在同样码率下做了 画质 > 帧间信息 的取舍
