### ISSUE TITLE
bug: 手动索引视频文件后导致webui报错

### ISSUE THREAD

**Issue by TranscendMa** [yuka-friends/Windrecorder#194]
我认为这可能是一个bug，触发经过如下：
- 从0.0.15更新到0.0.18
- 运行 `\extension\install_img_embedding_module` 下 `uninstall_img_embedding_module_卸载图像嵌入模型.bat` 删除已经安装的文件
- 运行 `install_img_embedding_module_安装图像嵌入模型.bat` 安装了新的语义模型
- webui界面此时能够使用图像语义搜索
- 发现可以手动为之前的视频添加索引，于是运行 `\extension\index_img_embedding_for_all_videofiles` 下 `index_img_embedding_for_all_videofiles.bat`，由于视频文件有900多个，只索引20个文件
- 索引完成后，运行Windrecorder，进入webui界面，提示如下：
> TypeError: 'NoneType' object is not subscriptable
![屏幕截图 2024-07-07 212018](https://github.com/yuka-friends/Windrecorder/assets/121599515/29a642e6-66fb-418e-9229-4189e1b8c1a3)

- 此时再对windrecorder的托盘图标进行操作就变得非常迟钝，甚至没有响应。Windows11的任务栏交互也变得奇怪。
- 在更新到0.0.18后的几次启动中，启动后直接进入webui也有较大概率触发此页，但往往等候片刻，刷新后正常。但本次并未有自行缓解。
- 经历相当长的等待后，卡顿消失，系统也恢复正常。
- 中间有若干次重新启动系统以及windrecorder

经过尝试，在这种情况下，点击其他任何的功能选单，如`全局搜索` `记忆摘要`，均为此报错页面。而只需要把日期向前一天，主页面即可正常，在此之后点击其他的功能选单，并未出现报错，并且功能，包括图像语义搜索均可正常使用。

据此认为可能是手动索引了最新一天的视频文件导致此故障，不排除直接退出软件造成了某些文件损坏之类的事情，当然也许跟新版的录制选项有所关联：
- 录制模式：自动灵活截图
- [ ] 只截图前台活动窗口(默认是勾选的，后续自己取消了勾选)
- [x] （节能）仅在电脑空闲时或接入电源时将截图转换为视频

**Comment by TranscendMa** [comment]
确认了一下，图像语义搜索其实并没有正常运行
![屏幕截图 2024-07-07 222438](https://github.com/yuka-friends/Windrecorder/assets/121599515/2afa1bf8-3631-4840-ae7c-413a2e58037d)

**Comment by Antonoko** [comment]
感谢反馈！这个报错看上去和截图模式的时间戳寻找逻辑逻辑有关，缺少处理“寻找当天最早与最晚时间戳时读取到了没有索引数据的（空）文件夹”的边缘情况，已尝试修复，可以通过执行 git pull 或运行更新脚本试试~

（语义搜索功能看上去可能仍是正常的，只不过现在的模型能力效果感觉比较差😭工程上也还缺少对一致向量结果的去重和reranking等处理（太菜了还没时间精力亲自研究这块…
