### ISSUE TITLE
托盘无应用图标，并且也没有找到其他办法找到现在WebUI使用的端口

### ISSUE THREAD

**Issue by breathiness** [yuka-friends/Windrecorder#203]
![Snipaste_2024-07-16_21-27-54](https://github.com/user-attachments/assets/27bbdbbe-34db-4906-920a-564906155921)

**Comment by Antonoko** [comment]
感谢反馈！请问是在打开 start_app.bat 后，有弹出录制的通知提示、但却没有出现托盘图标吗？如果是这种情况，方便提供下python版本（命令行执行`python -V`）、操作系统版本吗？此外，是之前可以正常使用、亦或是新安装后无法使用呢？

如果没有弹出录制通知提示，可能是程序没有正常执行，可以在windrecorder根目录下新建一个名为`DEBUGMODE.txt`的空文件再执行`start_app.bat`，观察其中输出的指令、还有使用记事本打开观察`cache/logs/wr.log`中的日志信息。如果打开`start_app.bat`命令行后一闪而过关闭，可以右键编辑，在最后添加一行pause后再打开，观察其中报错内容进行反馈。

**Comment by breathiness** [comment]
> 感谢反馈！请问是在打开 start_app.bat 后，有弹出录制的通知提示、但却没有出现托盘图标吗？如果是这种情况，方便提供下python版本（命令行执行`python -V`）、操作系统版本吗？此外，是之前可以正常使用、亦或是新安装后无法使用呢？

是的，我设置的是开机自动打开。在路径里看缓存是有正常在录制的。再打开 start_app.bat 有弹出已经在托盘运行的通知提示，但却没有出现托盘图标。
之前一直可以正常使用，WebUI也可以正常进入。但不知道从什么时候开始托盘图标就没了。
Python 的版本： 3.10.9
系统版本：Windows 11 专业版 21H2 22000.2538

**Comment by Antonoko** [comment]
好神奇0 0……Windows中有个设置可以查看是否显示托盘图标，也许可以先检查看看（但既然展开了也没有，可能就是没有注册到托盘了…因为这部分功能是用pystray这个库来实现的，如果是它本身的bug就比较黑箱难以排查了… 

> 可以在windrecorder根目录下新建一个名为DEBUGMODE.txt的空文件再执行start_app.bat，观察其中输出的指令、还有使用记事本打开观察cache/logs/wr.log中的日志信息

如果方便的话，可以参照这个步骤观察看看日志、有无特别的输出或者信息可以补充提供👆

![image](https://github.com/user-attachments/assets/01d57606-9e28-45ad-9831-a8e950ab002d)

**Comment by breathiness** [comment]
DEBUGMODE没有输出，我之后重启之后看看吧。

有什么其他方法可以看到使用的是哪个端口吗？这个端口好像不固定，用之前的地址是看不到的。如果有其他查看的方法我先应急用一下。

**Comment by breathiness** [comment]
DEBUGMODE没有输出，我之后重启之后看看吧。

有什么其他方法可以看到使用的是哪个端口吗？这个端口好像不固定，用之前的地址是看不到的。如果有其他查看的方法我先应急用一下。

**Comment by Antonoko** [comment]
> 有什么其他方法可以看到使用的是哪个端口吗？这个端口好像不固定，用之前的地址是看不到的。如果有其他查看的方法我先应急用一下。

托盘本质上是用界面串起了`record_screen.py`,`webui.py`两个脚本，可以通过以下步骤来手动查看 webui：

1. 在windrecorder根目录下启动命令行，执行命令`poetry shell`进入虚拟环境
2. 执行命令`streamlit run webui.py`启动webui，此时可以在命令行中看到地址。如果想手动指定端口，可以执行`streamlit run webui.py --server.port 端口号`
3. 如果需要手动录制，同理执行命令`python record_screen.py`

**Comment by breathiness** [comment]
好的，可以了。只是每次进入都要用上面的方法来指定端口吗？有什么方法可以让软件每次打开都使用固定的端口？

**Comment by Antonoko** [comment]
> 好的，可以了。只是每次进入都要用上面的方法来指定端口吗？有什么方法可以让软件每次打开都使用固定的端口？

由于打开 windrecorder 后并不会自动启动 webui，在没有托盘图标的情况下如果要进入 webui、仍然需要先手动启动后才能进入。因此你可以先在目录下执行`git pull`更新后，在目录下新建一个 `webui.bat`文件 ，内容如下：

```bat
@echo off
title Windrecorder
cd /d %~dp0
for /F "usebackq tokens=*" %%A in (`python -m poetry env info --path`) do call "%%A\Scripts\activate.bat"
streamlit run webui.py --server.port 28410
pause
```

这样就可以通过双击这个批处理文件来自动执行以上操作了，之后可为这个文件创建快捷方式后在其他地方打开

**Comment by breathiness** [comment]
非常感谢，已经可以了

**Comment by breathiness** [comment]
非常感谢，已经可以了

**Comment by breathiness** [comment]
没有任何预兆的，托盘图标回来了。
![图片](https://github.com/user-attachments/assets/02189d1d-ebf8-4474-bcfe-49342e80625b)
