### ISSUE TITLE
想问一下新OCR大概多久能使用？

### ISSUE THREAD

**Issue by DoiiarX** [yuka-friends/Windrecorder#210]
新OCR大概多久能使用？

我看到有好几个PR，但是似乎都没有合并。

**Comment by Antonoko** [comment]
收到反馈！在做了在做了！……（希望8～9月可以上一部分，比如基于onnx的paddle）

**Comment by Antonoko** [comment]
加入了，欢迎尝试！

测试结果参考：https://github.com/yuka-friends/Windrecorder/blob/main/__assets__/third_party_ocr_engine_benchmark_reference.md

**Comment by DoiiarX** [comment]
请教一下如何重新ocr之前的内容。

**Comment by Antonoko** [comment]
> 请教一下如何重新ocr之前的内容。

可以把视频文件名的`-OCRED`批量替换改为`-INDEX`，这样程序在启动时会回滚这些视频的数据并重新进行索引（可以先备份数据库后操作
