### ISSUE TITLE
Can't install, timeout connecting to https://pypi.tuna.tsinghua.edu.cn/simple

### ISSUE THREAD

**Issue by TangentFoxy** [yuka-friends/Windrecorder#211]
```
-git: updating repository
Already up to date.
-updating dependencies
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001702A632990>, 'Connection to pypi.tuna.tsinghua.edu.cn timed out. (connect timeout=15)')': /simple/poetry/
```

This repeats until it gives up, tries to move forward anyhow, and then fails because this failed.

**Comment by Antonoko** [comment]
Thanks for your feedback. Could you please supply your approximate region and network provider? In your region, does the link https://pypi.tuna.tsinghua.edu.cn/simple/ load correctly when you open it directly in a browser? It is a mirror source used to supplement downloads in areas with poor network. I am not sure how well it works in various places around the world, further research is needed...

**Comment by Antonoko** [comment]
I added pypi as the default mirror source and added additional supplementary mirror sources. You can try to run `install_update.bat` again to update the installation.

**Comment by TangentFoxy** [comment]
I believe I was connected through Bolivia at the time.

At the very least, I would suggest making the installer not attempt to continue when impossible due to a connection error. It would be far better if it could use alternate sources in the event an error occurs.

**Comment by TangentFoxy** [comment]
Worked! Any tips for someone who has no idea what they're doing with this yet?
