### ISSUE TITLE
"1Password" in window title should skip recording by default

### ISSUE THREAD

**Issue by TangentFoxy** [yuka-friends/Windrecorder#212]
While I think the current defaults are good, I recommend adding "1Password" (since KeePass is there).

I was going to say to add "New Tab" instead of "New Tab - Google Chrome" so that it works for multiple browsers and tools with a tab interface that uses the same terminology, but I'm not sure where window title is pulled from, and I just noticed that Firefox might be using "Mozilla Firefox" as its "New Tab" window... which sucks because it also includes Mozilla Firefox for *every* window.

**Comment by Antonoko** [comment]
Good idea, some commonly used passwords and sensitive information applications have been added to the preset settings. These are set based on my personal usage habits, so they may not be comprehensive, feel free to provide edge cases.

**Comment by TangentFoxy** [comment]
> Maybe it can be set to "Search with Google or enter address" (the element that usually appears in new tab)

That sounds good to me, I am not familiar with that appearing in a place where there is useful information. (Personally, I've just switched to Vivaldi, so I can no longer provide useful information related to Firefox.)
