### ISSUE TITLE
Cannot save settings on fresh install?

### ISSUE THREAD

**Issue by TangentFoxy** [yuka-friends/Windrecorder#213]
(I'm just guessing that maybe the fact that I haven't been running the program long enough to have saved data accessible via the webui might be why it failed?)

![image](https://github.com/user-attachments/assets/b595be79-65e0-44af-b46b-40de80afcbed)

**Comment by Antonoko** [comment]
Thanks for the feedback, fixed. Forgot to check if the folder exists before cleaning it...
