### ISSUE TITLE
微信OCR安装时会出现对带空格路径识别有误的问题

### ISSUE THREAD

**Issue by sutangar** [yuka-friends/Windrecorder#216]
在install_wechat_ocr的 _test_install.py 脚本中，处理包含空格的路径时存在潜在问题。目前的更改目录和追加路径的方法未考虑路径中包含空格的情况，可能会导致类似 'E:\Program' is not recognized as an internal or external command 的错误。

**Comment by Antonoko** [comment]
感谢反馈，我修、
