### ISSUE TITLE
运行install_update.bat后显示无windrecorder模块

### ISSUE THREAD

**Issue by zero617** [yuka-friends/Windrecorder#220]
Traceback (most recent call last):
  File "E:\Windrecorder\\onboard_setting.py", line 7, in <module>
    from windrecorder import __version__, utils
ModuleNotFoundError: No module named 'windrecorder'
请按任意键继续. . .

**Comment by Antonoko** [comment]
感谢反馈，看上去像是脚本没能成功进入虚拟环境与当前目录、从而搜寻不到文件夹下的windrecorder模块，请问方便提供下运行系统、python版本等环境信息以及可能复现的步骤、其他可能可疑的信息吗？🤔比如在此报错之前，提示未能成功安装poetry等信息？

可以尝试在目录下的命令行依次执行：
1. poetry shell
2. python
3. from windrecorder import __version__
4. __version__

如果正常进入虚拟环境，会得到如下执行结果：
![image](https://github.com/user-attachments/assets/e2e59e25-9602-4ca7-b98d-ce8510922aac)

**Comment by zero617** [comment]
重新拉取后可以了
