### ISSUE TITLE
更新最新版后运行 start_app.bat 后不能正常启动

### ISSUE THREAD

**Issue by lsy223622** [yuka-friends/Windrecorder#232]
如题，命令行窗口闪了一下之后就消失了，没有弹出正常启动的通知，也没有出现托盘图标。
按照 start_app.bat 中的注释注释掉隐藏 CLI 的代码之后就能正常启动了，通知和托盘图标正常。
猜测为最新版更新的隐藏命令行窗口的方式立即自动隐藏会导致还没启动就中止了启动过程。

**Comment by Antonoko** [comment]
感谢反馈！请问一下系统环境是怎么样的呢？如果方便，可以帮忙按以下步骤协助排错：
1. 在 start_app.bat 中修改为如下代码：
```
@echo off
title Windrecorder
mode con cols=70 lines=10
color 75
echo.
echo   Initializing Windrecorder, please stand by...
echo.
echo   Please stay in this window until it disappears
echo.


@REM hide CLI, if need debugging, please comment it out.(to :begin)
if "%1"=="h" goto begin
start mshta vbscript:createobject("wscript.shell").run("%~nx0"^&" h",0)^&(window.close) && exit
::start mshta "javascript:new ActiveXObject('WScript.Shell').Run('%~nx0 h',0);window.close();" && exit
:begin

echo [%time%]: batch is running.
ping -n 2 127.0.0.1 > DEBUGMODE1.txt

cd /d %~dp0
for /F "tokens=* USEBACKQ" %%A in (`python -m poetry env info --path`) do call "%%A\Scripts\activate.bat"

python "%~dp0\main.py"
```
2. 执行一次bat，观察目录下是否有 DEBUGMODE1.txt（若有，在命令行窗口隐藏后的代码应该能被执行
3. 在 windrecorder 运行的情况下执行 bat，观察是否有弹窗提示已运行（若有，windrecorder 的 python 进程应该能正常被执行

**Comment by lsy223622** [comment]
系统是 Windows 11，Python 是 3.11.7。
执行这个 bat 也是闪了一下消失，目录下没有出现 DEBUGMODE1.txt。
用仓库里的 start_app.bat 注释掉隐藏 CLI 的代码之后运行，在这个状态下再运行你提供的这个 bat 还是闪一下消失，目录下没有出现 DEBUGMODE1.txt。

**Comment by Antonoko** [comment]
谢谢测试，我暂时想不到比较好的解决头绪和进行复现，所以目前回滚加入了对之前隐藏方式的兼容。如果目前新的一闪而过隐藏窗口不奏效，可以通过在目录下新建一个 `hide_CLI_by_python.txt`，这样启动时就会以原先兼容性的方式进行隐藏。

**Comment by yangcongwangba** [comment]
命令行窗口闪了一下之后就消失，没有托盘图标，在目录下新建一个 hide_CLI_by_python.txt后 

![Image](https://github.com/user-attachments/assets/e803d91d-18b6-4258-9dcc-e692350bdc7c)闪一下然后消失，没有托盘图标，没有出现DEBUGMODE1.txt文件，
在 start_app.bat 中修改为如下代码：
@echo off
title Windrecorder
mode con cols=70 lines=10
color 75
echo.
echo   Initializing Windrecorder, please stand by...
echo.
echo   Please stay in this window until it disappears
echo.


@REM hide CLI, if need debugging, please comment it out.(to :begin)
if "%1"=="h" goto begin
start mshta vbscript:createobject("wscript.shell").run("%~nx0"^&" h",0)^&(window.close) && exit
::start mshta "javascript:new ActiveXObject('WScript.Shell').Run('%~nx0 h',0);window.close();" && exit
:begin

echo [%time%]: batch is running.
ping -n 2 127.0.0.1 > DEBUGMODE1.txt

cd /d %~dp0
for /F "tokens=* USEBACKQ" %%A in (`python -m poetry env info --path`) do call "%%A\Scripts\activate.bat"

python "%~dp0\main.py"后
闪一下消失，出现DEBUGMODE1.txt文件，但依然没有托盘图标，系统是 Windows 11，Python 是 3.11.7

>
