### ISSUE TITLE
 一个无关的问题？关于软件展示图的配色和样式🧐

### ISSUE THREAD

**Issue by aka-phrankie** [yuka-friends/Windrecorder#234]
请问这些图片是怎么做出来的，是靠直觉审美使用 Figma 或类似软件拼贴设计的咩，还是靠着开发者对渐变配色和版式的设计经验做出来的？

🧙感觉非常舒服，想了解一下相关心得或者工具链。

尤其是第三个脑图，是使用 [Coggle](https://coggle.it/) 做出来的吗。非常的精美，功能直观，大多数开发者不想做富有表现力的图。

![](https://github.com/yuka-friends/Windrecorder/raw/main/__assets__/product-header-cn.jpg)

![](https://github.com/yuka-friends/Windrecorder/raw/main/__assets__/product-preview-cn.jpg)

![](https://github.com/yuka-friends/Windrecorder/raw/main/__assets__/how-it-work-sc.jpg)

**Comment by Antonoko** [comment]
谢谢你的肯定和提问！😭主要原因是我本职工作还算是（产品）设计师……做开发特别业余、

是的！这些图是在 figma 中画的，包括原理流程图也是（感觉比较方便）。我感觉对于一个产品，能有清晰直接的视觉说明、让人直接接触产品本身长什么样很重要（扩大吸引潜在用户的这层漏斗），同时“设计”也能强化信任感（对于这样注重隐私的工具也很重要）。

（目前力所能及设计比较多的也是这些偏介绍传达的部分，受限于开发能力和技术栈选择，对于产品本身的体验设计还有很多能做的，希望未来有机会和时间慢慢改进…

![image](https://github.com/user-attachments/assets/ba94c3ef-8b84-4ed2-9111-2164cf49b0ad)
