### ISSUE TITLE
自动灵活截图下Python 占用大量CPU

### ISSUE THREAD

**Issue by Steven52065** [yuka-friends/Windrecorder#237]
![image](https://github.com/user-attachments/assets/f74aa4ee-800e-451a-91bc-b51f63a048c4)

台式机，i5-12600KF,RTX3060
设置为自动灵活截图、只截图前台活动窗口、（节能）仅在电脑空闲时或接入电源时将截图转换为视频
隔一段时间会出现如图所示的极高CPU占用，持续大概两分钟时间，期间非常影响电脑使用  
我目前的解决方法是手动在任务管理器里面给这个进程设置“效能模式”，这样好像会降低这个进程的CPU占用优先级
手动关掉Windrecorder后这个进程消失，可以确定这个Python是Windrecorder使用的

**Comment by Antonoko** [comment]
感谢反馈，台式机在接入电源检测中永远会是 True，因此会在每段片段录制结束时自动转换为视频。这里应该需要区分一下笔记本和台式机的不同设置策略……

**Comment by Steven52065** [comment]
> 感谢反馈，台式机在接入电源检测中永远会是 True，因此会在每段片段录制结束时自动转换为视频。这里应该需要区分一下笔记本和台式机的不同设置策略……
> 
> （设置为“效能模式”感觉是个好办法，转换视频是通过另一个线程完成的、不会阻塞截图识别的线程，理应为了其他计算机工作是接受降低完成速度、换取节能

设置为“效能模式”目前基本不影响正常使用，但是一旦Windrecorder或者计算机重启，就必须重新设置一次“效能模式”，有些麻烦  
希望是可以自动设置为“效能模式”，或者控制一下“转换视频”占用的CPU核心数，或者保留一个手动执行“转换视频”的按钮
大佬辛苦了OTZ

**Comment by Antonoko** [comment]
如何能让程序自动在“效能模式”下运行、限制视频合成占用待未来研究和测试，总之先把新的策略更新了上去…… 这样台式机在非空闲时应该也不会自动合成视频了
![image](https://github.com/user-attachments/assets/cc2764be-9780-411d-ba1d-1a9b7e02e566)
