### ISSUE TITLE
Mac 支持如何？

### ISSUE THREAD

**Issue by Ymriri** [yuka-friends/Windrecorder#242]
Mac 支持如何？

**Comment by Antonoko** [comment]
不支持捏，可以寻找 [README](https://github.com/yuka-friends/Windrecorder#:~:text=what%20other%20tools%20provide%20similar%20functions%3F) 底部提及的替代品。

**Comment by ASC8384** [comment]
我预计在一个月后尝试适配一下Mac，最近太忙了
