### ISSUE TITLE
[求助]程序在v0.0.28无法启动后，也无法正常升级到v0.0.29

### ISSUE THREAD

**Issue by TranscendMa** [yuka-friends/Windrecorder#257]
### 问题描述：
启动失败事件应该发生在11月的某日，直到我注意到windrecorder的托盘图标不见了。
手动运行`start_app.bat`后窗口一闪而过，但显然程序没有正常启动，经过数分钟后也未见托盘图标出现。

### 使用环境说明：
- Windows 11 23H2 专业版
- python等依赖先前已按照readme正确安装且正常运行，未手动修改环境变量
- windrecorder安装在`D:\Apps\Tools\Windrecorder\`下
- 使用了视觉模型extension
- 在更新到 v0.0.28 之后，正常运行了有一段时间，期间做出的更改：将灵活截图模式换回FFMPEG录制模式 (原因是灵活截图模式总是会隔段时间遗漏掉一些内容)

### 依次尝试过的解决方法：
- 运行`install_update.bat`，与先前更新时出现的内容差不多，但是最后的高亮部分明显不一样，显示如下：
```
No conda env active, defaulting to base
- 0.0.5 update routine
- 0.0.9 update routine
- 0.0.12 update routine
renamed userdata\videos\2024-07\2024-07-07_09-38-00-OCRED-ERROR.mp4 to userdata\videos\2024-07\2024-07-07_09-38-00-OCRED-ERROR1.mp4
renamed userdata\videos\2024-07\2024-07-07_17-27-12-OCRED-ERROR.mp4 to userdata\videos\2024-07\2024-07-07_17-27-12-OCRED-ERROR1.mp4
renamed userdata\videos\2024-07\2024-07-07_17-42-45-OCRED-ERROR.mp4 to userdata\videos\2024-07\2024-07-07_17-42-45-OCRED-ERROR1.mp4
renamed userdata\videos\2024-07\2024-07-07_19-48-53-OCRED-ERROR.mp4 to userdata\videos\2024-07\2024-07-07_19-48-53-OCRED-ERROR1.mp4
Loading onboard setting, please stand by...
Traceback (most recent call last):
  File "D:\Apps\Tools\Windrecorder\\onboard_setting.py", line 50, in <module>
    from windrecorder import file_utils, ocr_manager  # NOQA: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Apps\Tools\Windrecorder\windrecorder\ocr_manager.py", line 15, in <module>
    from windrecorder import file_utils, record_wintitle
  File "D:\Apps\Tools\Windrecorder\windrecorder\record_wintitle.py", line 17, in <module>
    from windrecorder.db_manager import db_manager
  File "D:\Apps\Tools\Windrecorder\windrecorder\db_manager.py", line 863, in <module>
    db_manager = _DBManager(
                 ^^^^^^^^^^^
  File "D:\Apps\Tools\Windrecorder\windrecorder\db_manager.py", line 30, in __init__
    self.db_update_table_product_routine()  # 程序更新后调整数据结构
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Apps\Tools\Windrecorder\windrecorder\db_manager.py", line 126, in db_update_table_product_routine
    self.db_ensure_row_exist(
  File "D:\Apps\Tools\Windrecorder\windrecorder\db_manager.py", line 110, in db_ensure_row_exist
    cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {column_type};")
sqlite3.OperationalError: no such table: video_text
请按任意键继续. . .
```
重试多次发现并未正常更新到v0.0.29。

- 按照：

> [!NOTE]
> 如果打开`start_app.bat`后命令行窗口一闪而过、**过了一段时间 捕风记录仪 仍没有出现在系统托盘中**，请在目录下创建一个名为`hide_CLI_by_python.txt`的文件并打开`start_app.bat`重试； [#232](https://github.com/yuka-friends/Windrecorder/issues/232)

已执行，出现类似先前版本的弹窗，但是多了一个页面，内容如图。检查进程可以观测到python和用于启动的CMD进程相继退出，目录下也没有出现 `DEBUGMODE1.txt`。
![image](https://github.com/user-attachments/assets/7fddf2ad-dd45-40c1-8d6d-2e7f28b13664)

- 按照：

> 如果无法升级，请尝试在目录下执行命令 `git fetch origin | git reset --hard origin/main` 后运行 `install_update.bat`

已执行，但重新运行`start_app.bat`或`install_update.bat`并无改善。

### 进一步解决
- 我想找到软件数据目录的结构以推断发生时间或重置软件，但是并没有弄明白。
- 在试图分析时注意到：Windrecorder的安装文件夹总大小达到64.4 GB，其中：
- `.venv`占用1.45 GB，其中23,452 个文件，2,584 个文件夹
- `cache` 占用12.1 GB，其中18,013 个文件，105 个文件夹
- `userdata`占用50.6 GB，其中3,066 个文件，15 个文件夹
- 当前分区可用空间11.1GB

如果您有进一步的排查建议，请指出，谢谢！

**Comment by Antonoko** [comment]
感谢翔实的报告反馈！根据提供的报错，看上去是在对数据库文件操作时，没有找到其中的表格video_text。您可以在 `Windrecorder\userdata\db` 文件夹下检查数据库文件，看看是否都是 用户名_2024-12_wind.db 类似的数据库文件、没有其他的杂项（其中后缀为_TEMP_READ的文件为临时数据库、可以删除试试）。如果均是，可以使用任意的sqlite数据库查看器（比如本地的[DB Browser](https://sqlitebrowser.org/)或其他在线工具），查看.db数据库文件内是否有名为video_text的表格（这也是唯一一张表）
![image](https://github.com/user-attachments/assets/fa59d552-1457-48e9-8e82-a7cdda2ed2e0)

（我想我需要在db读取前，加入检测文件是否合法的判断… 现在是只要在db文件夹下的文件就会读取，可能大概率是读到了不是数据库文件的文件导致报错阻塞

**Comment by TranscendMa** [comment]
感谢您的回复！
我在检查`\userdata\db`时确实发现了符合以上描述的文件，而且这些临时文件与对应的的数据库文件看上去大小相同。此外，还有几个不太寻常的文件，一个文件名为`default_2024-05_wind.db`，而另一个是0字节大小的`用户名_2024-11_wind.db-journal`文件。
![image](https://github.com/user-attachments/assets/3f5d94f8-8520-4681-a02d-119d064c9195)

我在尽可能减少改动的情况下进行尝试：
先是删除了所有后缀为`_TEMP_READ`的文件，windrecorder并不能正常启动，接着我删除了这个名为`用户名_2024-11_wind.db-journal`的空文件，现在运行`start_app.bat`可以正常启动、而且可以正常更新到v0.0.29了。

不过这些后缀为`_TEMP_READ`的文件似乎是程序正常运行时产生的，而当发生某种错误时，会导致`_TEMP_READ`的文件内数据出现损坏从而导致程序无法启动。目前我不清楚在什么样的情况下会导致如此问题，如果再次遇到，我会尝试记录下来。


另外，在webui进行操作的时候，有时会出现“两个标题”的情况（不过这不是什么恶性问题，通常耐心等待十几秒钟左右即可消失）
![image](https://github.com/user-attachments/assets/121a74d8-9d14-4a20-9b90-e030440d5224)
如果在以后的更新中可以优化一下那就更好了😄

**Comment by TranscendMa** [comment]
应该是那个0字节大小的`.db-journal`文件导致了此异常，但不清楚它是如何出现的。

**Comment by Antonoko** [comment]
.db-journal是sqlite在事务处理中的临时文件，可能出于某种情况未处理完成就被中断、从而导致没能成功回收。这确实是数据库检验的一个大问题，在读取前应该检测、并做失败的兜底，我想想哪里需要改、加上判断条件…

> 另外，在webui进行操作的时候，有时会出现“两个标题”的情况
这个是streamlit的界面更新机制导致的，它的页面渲染是单线程阻塞的、加上程序效率并不是特别高，因此等页面顺序地加载完需要一些时间…（实在不擅长写程序，报以未来可能会有大佬优化或重构查询前端的可能性（
