### ISSUE TITLE
优化“当前活动”策略

### ISSUE THREAD

**Issue by linchuanXu** [yuka-friends/Windrecorder#30]
现在捕捉用户当前活动是直接录屏（截图），会造成大量的无关背景内容

manic time的策略是：
1.间隔时间截图
2.当前激活窗口切换时，截图
3.可以只截图当前激活的窗口，也就是只截图活动内容

windrecorder也可以加入当前激活窗口判断、当前激活窗口的标题获取、鼠标移动判断、访问网络读取磁盘的应用程序详情（可以加入黑名单机制：我玩游戏的时候不需要录屏和ocr，很卡顿）、甚至是键盘输入情况判断，现在程序的逻辑和业务都比较简陋，可以完全先把manic time这个产品全抄完。

**Comment by Antonoko** [comment]
久等了！支持仅录制前台活动窗口、能根据截图帧自动识别与判断、具有更低能耗和更灵活的“自动灵活截图（使用 MSS）”模式已加入，欢迎更新尝试~
