### ISSUE TITLE
bug: Windows Terminal 下背景颜色显示异常

### ISSUE THREAD

**Issue by Clouder0** [yuka-friends/Windrecorder#37]
![image](https://github.com/Antonoko/Windrecorder/assets/41664195/3f3ee498-fa55-49a1-984f-f84347e4d1f1)

另外，`start_webui` 的背景颜色删除 bat 中的 `color` 设置后正常。而 `start_recording` 背景颜色仍然有问题。

**Comment by Clouder0** [comment]
看代码里面有不同状态设置不同颜色的操作，这似乎是 intended behaviour？该配色让文字完全无法阅读，不知道是怎么考虑的？

**Comment by Antonoko** [comment]
配色看上去是不符合预期的，符合预期的配色看上去大概是这样的几种状态🤔：
![image](https://github.com/Antonoko/Windrecorder/assets/11193477/ae979bab-0754-42ec-8c5a-9b95cc2dbf84)

（我猜测可能是W indows terminal 终端的主题配色或相关设置干扰影响了预期表现）

**Comment by Clouder0** [comment]
嗯对，使用了不同的 [Color schema](https://learn.microsoft.com/zh-cn/windows/terminal/customize-settings/color-schemes) 导致的，我这里用的是 tokyonight.

**Comment by Antonoko** [comment]
工具正在逐渐移除 CLI，此项 issue closed
