### ISSUE TITLE
BUG: 看起来是数据读取/保存逻辑错误

### ISSUE THREAD

**Issue by welann** [yuka-friends/Windrecorder#39]
`videos\2023-11` 文件下的文件 保存有14~17日的视频 标题类似于 `2023-11-17_15-28-01-OCRED.mp4`
但是webui上无法索引，停留在14日后无法更新

**Comment by Antonoko** [comment]
看上去是遇到什么阻塞、导致 webui 没有能读取最新的数据库而读取了旧的缓存数据库，可以在 start_record.bat 没有进行索引、或关闭了的情况下，试试将db目录下以 `_TEMP_READ.db` 后缀的文件删除再打开 webui 试试呢？
