### ISSUE TITLE
录制出来的视频在webui上能正常播放，播放本地视频却显示花屏

### ISSUE THREAD

**Issue by zhenghewo** [yuka-friends/Windrecorder#43]
在potplayer上是花屏
在windows自带播放器上，无法播放

在webui & 腾讯视频播放器上,能正常播放

![image](https://github.com/Antonoko/Windrecorder/assets/26183888/e3b7d561-440a-48e1-98ae-641e4d9e123c)
![image](https://github.com/Antonoko/Windrecorder/assets/26183888/4858b8e8-de74-4986-bf4c-3475d0e88f81)

**Comment by ASC8384** [comment]
我使用的是 Firefox 120.0.1 (64 位)，无法在 webui 上播放，本地可以。

ws://localhost:8501/_stcore/stream 的状态是 101 Switching Protocol

![图片](https://github.com/yuka-friends/Windrecorder/assets/29878345/7cb767c3-d7e1-46a1-ae17-b1298c5ad886)
