### ISSUE TITLE
bug: 使用第三方锁屏时，仍会处于录制状态

### ISSUE THREAD

**Issue by zhenghewo** [yuka-friends/Windrecorder#50]
![image](https://github.com/yuka-friends/Windrecorder/assets/26183888/b3cdcd82-0700-4a2f-8f97-9173447b5990)

录制选项已经设置为1分钟无变化就暂停了，但是锁屏后，有时仍会持续录制
![image](https://github.com/yuka-friends/Windrecorder/assets/26183888/78c3b9e9-9e13-4764-bff0-550055f54d6e)

这种情况下是判断哪部分仍在变化呢，因为看录制的视频，锁屏界面上的时间是每5分钟才变化一次
![image](https://github.com/yuka-friends/Windrecorder/assets/26183888/ce676a3a-bfa8-465b-81b9-cce27b0a36a9)

也尝试过打开一个空白txt，最大化显示，然后再锁屏，也是锁屏后，有时仍会持续录制

**Comment by Antonoko** [comment]
锁屏界面是由第三方应用提供的吗？目前工具仅支持检测 Windows 原生的锁屏与熄屏状态，第三方的锁屏界面程序则可能使用与其他情况一致的、通过检测画面内容变化的方式来控制是否暂停录制，这种情况下画面的时间变化可能会干扰检测（可以通过命令行输出来查看画面未变化时间）。未来可能将加入对前台进程名称的记录，借此也可以加入当检测到前台进程为xxx时暂停录制。

目前录制切片是由许多个15分钟的视频构成的，如果在刚开始录制时“检测到画面一分钟内无变化”，也将会录制完剩余的15分钟时间，然后程序会根据最后的“检测到画面一分钟内无变化”状态，来判断是否继续录制下个15分钟切片（如果录制最后画面刚好是一分钟无变化的状态，那么下段视频将不会开始录制，直到画面出现变化）。目前的技术选型对此控制还不是太灵活，未来可能会调整录制的方式、或通过加入更便捷的【暂停/继续录制】的托盘菜单手动控制。

enhancement：
- 加入对前台进程名称的记录；加入对前台名称的录制排除；
- 调研更灵活的录制方法；

**Comment by zhenghewo** [comment]
是的，锁屏是由联想电脑管家控制的，换成Windows 原生的锁屏后能实现暂停录制了
提升的话，也可以考虑加入一些快捷键来 暂停/继续录制，如检测到 win+L就暂停

**Comment by Antonoko** [comment]
加入跳过特定前台应用功能啦！可以更新试试看。在开始录制后使用三方锁屏，再在 cache\win_title 下的 csv 最后找到锁屏的应用名，把它添加到跳过项后应该就能在锁屏时不录制了。

![image](https://github.com/yuka-friends/Windrecorder/assets/11193477/0a596ce8-c10e-4dfc-a963-8208613df694)
