### ISSUE TITLE
使用时ffmpeg占用大量内存

### ISSUE THREAD

**Issue by ASC8384** [yuka-friends/Windrecorder#54]
![图片](https://github.com/yuka-friends/Windrecorder/assets/29878345/cf4ef0bc-f462-42f6-8a09-36de2a60b82e)
如图所示，内存总占用约 10G，请问这是正常现象吗？
主屏幕是4K屏。
（~~顺便请问多屏开发的优先级高么~~）

**Comment by Antonoko** [comment]
“自动灵活截图（使用 MSS）”模式已加入，可以作为ffmpeg的替代方案，它的开销更低更节能、占用系统资源也更低
