### ISSUE TITLE
bug: 录制的视频文件只剩下左上部分的画面，原因未知

### ISSUE THREAD

**Issue by B1lli** [yuka-friends/Windrecorder#90]
今天检查视频文件，发现最近一段时间的视频文件都只剩下左上部分的画面
![image](https://github.com/yuka-friends/Windrecorder/assets/62195677/83aebd11-81d9-4408-b17a-f3d8a8505557)

回去检查了一下这个现象从什么时候开始出现，发现是从自己元旦那会开始玩博德之门3的时候，打开博德之门3之后在游戏内和游戏外切换了数次，随后就这样了，我的电脑是笔记本电脑，N卡，开了独显直连模式，可能和独显处理信号切换有关

该问题在重启`start_app.bat`后消失

**Comment by B1lli** [comment]
可能的临时解决办法：允许用户自定义一个时间间隔，到达该间隔时自动重启一下`start_app.bat`

**Comment by Antonoko** [comment]
感谢反馈！目前的录制逻辑是每次录制时都重新读取屏幕分辨率，如果在录制下一个15分钟片段的中途改变了分辨率便会出现这样的问题（我最近开始玩游戏时也注意到了😵‍💫，打算接下来把策略改为只在`start_app.bat`打开时读取一次分辨率，之后便固定下来；config 中也提供非显式的选型允许用户自定义固定分辨率）

![image](https://github.com/yuka-friends/Windrecorder/assets/11193477/cebd8ad6-b571-4dea-820e-a4245c2fc5b2)

**Comment by ASC8384** [comment]
感觉可以在托盘加个重启功能
```python
def on_restart(icon: pystray.Icon, item: pystray.MenuItem):
    """重启当前的python程序"""
    icon.notify(message=_t("tray_restart"), title=_t("tray_restart"))
    logger.info("Restarting Windrecorder...")
    os.execl(os.execl, os.path.abspath(os.path.abspath(__file__)), * sys.argv)
```
但这么写似乎没用。。。

**Comment by Antonoko** [comment]
支持仅录制前台活动窗口、能根据截图帧自动识别与判断、具有更低能耗和更灵活的“自动灵活截图（使用 MSS）”模式已加入，作为ffmpeg的替代方案、应该可以自适应不同窗口与分辨率大小，欢迎更新尝试~
